### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by mashuDuek** [jessewarren-aa/strifechat#1]
Looking good!!! 
Couple things: 
1. How will you handle DMs? Will they be instances of channels? If thats the case then name/description could be null? Or maybe just description? 
2. The fact that you have a reactions table would imply that you're going to allow users to add reactions? I would make reactions have a `message_id` rather than a join table (`message_reactions`), and make sure that reactions have an `image_url` that are included in some list of possible reactions that you pre-set. 
3. Roles. You shouldn't really have more than a few roles (admin, owner, general - or something like that). I was thinking the permissions table could have a `role` string column, that should be included in your array of few roles. So in the `permissions` table you could have `role`, `user_id`, and `channel_id` (or `server_id` i think is more accurate).

**Comment by jessewarren-aa** [comment]
@mashuDuek 

1. From my current structure, I believe I would have to instantiate a private server with "one" channel for each private message between users, as a "private messages" server (my initial thought) with channels per user would be hard to utilize without users being able to see into other private messages they aught not to.

2. Addressed in sample state issue, if I'm reading it correctly.

3. The reason that I have three tables (`permissions`, `roles`, and `user_roles`) is because each server can choose to create roles or not. Each server starts with an "everyone" role by default and can choose to implement other roles. This way, I can have `permissions` house the specific permissions granted, I can have `roles` hold custom roles on each server as they are created, and I can have `user_roles` hold which user has what role on which server.

Please me know if this is adequate.

**Comment by mashuDuek** [comment]
For your third point, the custom roles thing i a little scary. Meaning, I can tell you this role is called "Captain" and I can specify the level of access they have? Also, you only care about the permissions for the current user, so when you send up servers, with each server you can send up current_user permissions. 

Did not understand point 1. I'll catch you at some point today to chat.
